import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import './styles.css';

const sbUrl=import.meta.env.VITE_SUPABASE_URL; const sbKey=import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=sbUrl&&sbKey?createClient(sbUrl,sbKey):null;
const demoUser={id:'demo-user',email:'demo@digitalheroes.golf',role:'subscriber',full_name:'Demo Subscriber'};
const seedCharities=[
 {id:'c1',name:'Fairway Futures Foundation',description:'Creates access to golf, coaching and community programmes for young people.',impact:'Junior golf access',featured:true},
 {id:'c2',name:'Green Fairways Trust',description:'Supports sustainable courses and local environmental projects.',impact:'Greener golf courses',featured:false},
 {id:'c3',name:'Golf For All',description:'Makes golf accessible to underserved communities through equipment and coaching.',impact:'Inclusive golf',featured:false}
];
function App(){
 const [user,setUser]=useState(null),[page,setPage]=useState('home'),[auth,setAuth]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[msg,setMsg]=useState(''),[scores,setScores]=useState(()=>JSON.parse(localStorage.getItem('dh_scores')||'[]')),[charity,setCharity]=useState(()=>localStorage.getItem('dh_charity')||'c1'),[plan,setPlan]=useState('monthly'),[draw,setDraw]=useState(null),[admin,setAdmin]=useState(false);
 useEffect(()=>{ if(supabase){supabase.auth.getSession().then(({data})=>setUser(data.session?.user||null)); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null));return()=>data.subscription.unsubscribe()}},[]);
 const login=async()=>{setMsg(''); if(supabase){const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg(error.message);else {setUser(data.user);setPage('dashboard')}}else{setUser({...demoUser,email});setPage('dashboard')}};
 const signup=async()=>{setMsg(''); if(!email||!password)return setMsg('Enter email and password'); if(supabase){const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name,role:'subscriber'}}});if(error)setMsg(error.message);else{setUser(data.user);setPage('dashboard')}}else{setUser({...demoUser,email,full_name:name||'Subscriber'});setPage('dashboard')}};
 const logout=async()=>{if(supabase)await supabase.auth.signOut();setUser(null);setPage('home');setAdmin(false)};
 const addScore=(e)=>{e.preventDefault();const f=new FormData(e.currentTarget),score=Number(f.get('score')),date=f.get('date'); if(score<45||score>150)return setMsg('Score must be between 45 and 150.');if(scores.some(x=>x.date===date))return setMsg('A score for this date already exists.');const next=[{score,date},...scores].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);setScores(next);localStorage.setItem('dh_scores',JSON.stringify(next));setMsg('Score saved.');e.currentTarget.reset()};
 const runDraw=()=>{const nums=[1,2,3,4,5].map(()=>Math.floor(Math.random()*9)+1);const pool=1200;const result={numbers:nums.join('-'),pool,tiers:[{match:'5-number',share:.4,amount:pool*.4},{match:'4-number',share:.35,amount:pool*.35},{match:'3-number',share:.25,amount:pool*.25}],date:new Date().toLocaleDateString()};setDraw(result);setMsg('Draw simulation completed.')};
 const selected=seedCharities.find(c=>c.id===charity);
 return <div className="app">
  <header><div className="brand" onClick={()=>setPage('home')}><span>DH</span> DIGITAL <i>HEROES</i></div><nav>{[['home','Home'],['charities','Charities'],['draw','The Draw']].map(([p,l])=><button className={page===p?'active':''} onClick={()=>setPage(p)}>{l}</button>)}{user&&<button onClick={()=>setPage('dashboard')}>Dashboard</button>}{user&&admin&&<button onClick={()=>setPage('admin')}>Admin</button>}</nav><div>{user?<button className="outline" onClick={logout}>Logout</button>:<button className="cta" onClick={()=>{setPage('auth');setAuth('login')}}>Join now</button>}</div></header>
  <main>
   {page==='home'&&<><section className="hero"><div><p className="eyebrow">PLAY • GIVE • WIN</p><h1>Your golf game can <em>give back.</em></h1><p className="lead">A modern golf membership combining performance tracking, monthly prize draws and meaningful charity impact.</p><div className="actions"><button className="cta" onClick={()=>{setPage('auth');setAuth('signup')}}>Become a member →</button><button className="ghost" onClick={()=>setPage('charities')}>Explore charities</button></div></div><div className="hero-card"><div className="sun"></div><div className="golfball">◉</div><p>MONTHLY DRAW</p><strong>₹1,200 prize pool*</strong><small>40% • 35% • 25% distribution</small></div></section><section className="stats"><div><b>5</b><span>latest scores tracked</span></div><div><b>10%</b><span>minimum charity contribution</span></div><div><b>3</b><span>draw winning tiers</span></div></section><section className="section"><p className="eyebrow">HOW IT WORKS</p><h2>Score. Enter. <em>Give.</em></h2><div className="cards"><Card n="01" t="Subscribe" d="Choose monthly or yearly membership."/><Card n="02" t="Record scores" d="Keep your five most recent golf scores."/><Card n="03" t="Support a cause" d="Direct at least 10% of your fee to a charity."/><Card n="04" t="Join the draw" d="Active subscribers enter the monthly prize draw."/></div></section></>}
   {page==='charities'&&<section className="section"><p className="eyebrow">CHARITY DIRECTORY</p><h1>Choose your <em>impact.</em></h1><p className="lead">Every subscriber selects a cause. Featured organisations are highlighted below.</p><div className="cards three">{seedCharities.map(c=><div className="card charity"><span className="tag">{c.featured?'FEATURED':'CHARITY'}</span><h3>{c.name}</h3><p>{c.description}</p><strong>{c.impact}</strong><button className="ghost" onClick={()=>{setCharity(c.id);localStorage.setItem('dh_charity',c.id);setPage(user?'dashboard':'auth');setAuth('signup')}}>Select charity</button></div>)}</div></section>}
   {page==='draw'&&<section className="section"><p className="eyebrow">THE DRAW</p><h1>Monthly <em>prize engine.</em></h1><p className="lead">The fixed pool is distributed automatically across three match tiers.</p><div className="draw-grid">{[['5-number','40%','Jackpot — rolls over if unclaimed'],['4-number','35%','Shared equally among winners'],['3-number','25%','Shared equally among winners']].map(x=><div className="draw-tier"><b>{x[0]}</b><strong>{x[1]}</strong><span>{x[2]}</span></div>)}</div>{admin&&<div className="panel"><h3>Admin simulation</h3><button className="cta" onClick={runDraw}>Run monthly draw</button>{draw&&<div className="result"><h2>Numbers: {draw.numbers}</h2>{draw.tiers.map(t=><p><b>{t.match}</b> — ₹{t.amount}</p>)}</div>}</div>}</section>}
   {page==='auth'&&<section className="auth"><div className="auth-box"><p className="eyebrow">DIGITAL HEROES</p><h1>{auth==='login'?'Welcome back':'Start your membership'}</h1>{auth==='signup'&&<input placeholder="Full name" value={name} onChange={e=>setName(e.target.value)}/>}<input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="cta full" onClick={auth==='login'?login:signup}>{auth==='login'?'Login':'Create account'}</button>{msg&&<p className="msg">{msg}</p>}<button className="link" onClick={()=>setAuth(auth==='login'?'signup':'login')}>{auth==='login'?'Create a new account':'Already have an account? Login'}</button></div></section>}
   {page==='dashboard'&&user&&<section className="section"><div className="dash-head"><div><p className="eyebrow">MEMBER DASHBOARD</p><h1>Hello, <em>{user.user_metadata?.full_name||user.full_name||'Golfer'}.</em></h1></div><button className="outline" onClick={()=>{setAdmin(!admin);setPage(admin?'dashboard':'admin')}}>{admin?'Subscriber view':'Admin demo'}</button></div><div className="dashboard-grid"><div className="panel"><span className="tag">SUBSCRIPTION</span><h2>{plan==='monthly'?'Monthly':'Yearly'} plan</h2><p className="status">● Active</p><div className="plan-switch"><button className={plan==='monthly'?'sel':''} onClick={()=>setPlan('monthly')}>Monthly</button><button className={plan==='yearly'?'sel':''} onClick={()=>setPlan('yearly')}>Yearly</button></div><button className="cta full" onClick={()=>setMsg('Stripe test checkout would open here. Configure Stripe keys before production.')}>Continue to payment</button></div><div className="panel"><span className="tag">YOUR CHARITY</span><h2>{selected.name}</h2><p>{selected.description}</p><select value={charity} onChange={e=>{setCharity(e.target.value);localStorage.setItem('dh_charity',e.target.value)}}>{seedCharities.map(c=><option value={c.id}>{c.name}</option>)}</select><p className="impact">Minimum contribution: <b>10%</b></p></div></div><div className="dashboard-grid"><div className="panel"><span className="tag">GOLF SCORES</span><h2>Last 5 scores</h2><form onSubmit={addScore} className="score-form"><input name="score" type="number" min="45" max="150" placeholder="Score 45–150" required/><input name="date" type="date" required/><button className="cta">Add score</button></form>{msg&&<p className="msg">{msg}</p>}<div className="score-list">{scores.length?scores.map(s=><div><b>{s.score}</b><span>{s.date}</span></div>):<p>No scores yet.</p>}</div></div><div className="panel"><span className="tag">WINNINGS</span><h2>₹0</h2><p>Total won</p><div className="mini"><span>Upcoming draw</span><b>Monthly</b></div><div className="mini"><span>Payment status</span><b>—</b></div><button className="ghost full" onClick={()=>setPage('draw')}>View draw details</button></div></div></section>}
   {page==='admin'&&<section className="section"><p className="eyebrow">ADMIN CONSOLE</p><h1>Full <em>control.</em></h1><div className="cards three"><div className="card"><span className="tag">01</span><h3>User management</h3><p>View profiles and subscription status.</p><button className="ghost">View users</button></div><div className="card"><span className="tag">02</span><h3>Draw management</h3><p>Configure logic, simulate and publish results.</p><button className="cta" onClick={()=>{setPage('draw');setAdmin(true)}}>Open draw</button></div><div className="card"><span className="tag">03</span><h3>Charity management</h3><p>Add, edit and manage featured causes.</p><button className="ghost" onClick={()=>setPage('charities')}>Manage charities</button></div><div className="card"><span className="tag">04</span><h3>Winner verification</h3><p>Review proof and mark payouts completed.</p><button className="ghost">Review winners</button></div><div className="card wide"><span className="tag">REPORTS</span><div className="metrics"><div><b>24</b><span>Total users</span></div><div><b>₹1,200</b><span>Prize pool</span></div><div><b>₹120</b><span>Charity contribution</span></div></div></div></div></section>}
  </main><footer><div className="brand">DIGITAL <i>HEROES</i></div><span>Golf performance • prize draws • charity impact</span></footer>
 </div>
}
const Card=({n,t,d})=><div className="card"><span className="tag">{n}</span><h3>{t}</h3><p>{d}</p></div>;
createRoot(document.getElementById('root')).render(<App/>);
